package com.example.filtros.filterView

enum class Filter() {
    NORMAL,NEGATIVO, GRISES, BRILLO, CONTRASTE, GAMMA, ROJO, VERDE, AZUL, SMOOTHING, GAUSSIAN_BLUR, SHARPEN, MEAN_REMOVAL, EMBOSSING, EDGE_DETECTION
}